### ISSUE TITLE
Display sizing on Raspberry Pi 3

### ISSUE THREAD

**Issue by matthewmgamble** [gustavosbarreto/electric-webview#6]
Following your comment on Screenly OSE issue #527 (https://github.com/wireload/screenly-ose/issues/527) I installed and setup electric-webview myself on a test raspberry pi.

After getting everything complied, the browser works, however, the display size is completely wrong.  When starting up, the app says:

"Unable to query physical screen size, defaulting to 100 dpi"

I tried setting the values as follows but it didn't help - the error goes away but the display is still broken:

export QT_QPA_EGLFS_WIDTH=1920 
export QT_QPA_EGLFS_HEIGHT=1080
export QT_QPA_EGLFS_PHYSICAL_WIDTH=177
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=100
export QT_QPA_EGLFS_DEPTH=24
export QT_QPA_EGLFS_ALWAYS_SET_MODE=1

For example, when I follow your example and try to load github.com, I only see github on about 1/5 of the screen even though I put electric-webview into full screen mode.

Any suggestions on how to get this working properly on a Raspberry pi?  Any advice would be greatly appreciated.

**Comment by gustavosbarreto** [comment]
Hi @matthewmgamble 

I had a similar issue on some monitor models and found a workaround following these instructions:

http://stackoverflow.com/a/36430185/7814972
http://elinux.org/RPi_Configuration

Keep me updated if you find a way to resolve this.
